# Generated by Django 5.2.7 on 2026-01-25 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student4c2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='', max_length=20)),
                ('session', models.CharField(default='', max_length=20)),
                ('hobbies', models.CharField(default='', max_length=100)),
                ('photo', models.BinaryField()),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
