# Generated by Django 5.2.7 on 2026-01-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apia01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenta01',
            old_name='lasstname',
            new_name='lastname',
        ),
    ]
